stages:
  - stage: destroy
    jobs:
      - deployment: destroy_terraform
        continueOnError: false
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: TerraformInstaller@0
                  displayName: 'install'
                  inputs:
                    terraformVersion: 'latest'

                - task: TerraformTaskV2@2
                  displayName: 'init'
                  inputs:
                    provider: 'aws'
                    workingDirectory: terraform
                    command: 'init'
                    backendServiceAWS: 'terraform-get-started'
                    backendAWSBucketName: 'terraform-get-started'
                    backendAWSKey: 'terraform.tfstate'

                - task: TerraformTaskV2@2
                  displayName: 'destroy'
                  inputs:
                    provider: 'aws'
                    workingDirectory: terraform
                    command: 'destroy'
                    environmentServiceNameAWS: 'terraform-get-started'